### ISSUE TITLE
Error with socket.io 2.0.3

### ISSUE THREAD

**Issue by jlfalcon** [losandes/socket.io-mongodb#9]
Hi,

I got this error trying to use this adaptor with socket.io 2.0.3:

> TypeError: this.adapter.addAll is not a function
>     at Socket.join (/var/www/chat_server/node_modules/socket.io/lib/socket.js:248:16)
>     at Socket.onconnect (/var/www/chat_server/node_modules/socket.io/lib/socket.js:303:8)
>     at /var/www/chat_server/node_modules/socket.io/lib/namespace.js:175:16
>     at nextTickCallbackWith0Args (node.js:419:9)
>     at process._tickCallback (node.js:348:13)

`var mongoAdapter = require('socket.io-mongodb');
io.adapter(mongoAdapter('mongodb://localhost:27017/chat', {
	collectionName: 'zk-chat'
}));`

Could you help me?

**Comment by holuspokus** [comment]
Hi,
no, sorry.
I tried under ./node_modules/socket.io-mongodb
Update socket.io-adapter to 1.1.1
edit package.json -> dependencies: "socket.io-adapter": "latest"
 npm update
-> no error, but doesnt work.

**Comment by trappedion** [comment]
I got the same problem. It seems the mongodb adapter is not implementing the "[addAll](https://github.com/socketio/socket.io-adapter/blob/6874ea4952346d1dfc80c53beaa2ec014fc024b7/index.js#L56)" method. I reverted to using socket.io 1.7.4.
